# Generated by Django 4.0.4 on 2022-05-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
