# Generated by Django 4.0.4 on 2022-05-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_category_options_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
